ticker: LTC
block: 1484499
confirmations: 1
port: 8000

node:
   type: btc
#   host: 34.219.117.248:9332
#   user: litecoin
#   pass: litecoin
   host: 52.166.56.104:8335
   user: bitcoin
   pass: local321
